import type { Metadata } from "next";
import { Tajawal } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/header";
import { Footer } from "@/components/layout/footer";
import { WhatsAppFloat } from "@/components/ui/whatsappicon";
import { PobUp } from "@/components/ui/poub";

const tajawal = Tajawal({
  subsets: ["arabic", "latin"],
  weight: ["200", "300", "400", "500", "700", "800", "900"],
  variable: "--font-tajawal",
});

export const metadata: Metadata = {
  title: "Citizenship By Investment",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={tajawal.className}>
      <body className="antialiased relative">
        <Header />
        {children}
          <WhatsAppFloat
        phoneNumber="+962792919995"
      />
      <PobUp/>
        <Footer/>
      </body>
    </html>
  );
}